### ISSUE TITLE
A ToDo list that implements WinAppDriver commands.

### ISSUE THREAD

**Issue by kzO8Xekb** [kzO8Xekb/win-app-driver#1]
# List of WinAppDriver commands supported by closures (ver. 0.1.29)
Commands with a check in the list below have been tested to work.

## actions.lisp (ver. 0.1.24 split from api.lisp)
- [x] :button-down
- [x] :button-up
- [x] :click
- [x] :doubleclick
- [x] :move-to
- [x] :touch-click
- [x] :touch-double-click (ver. 0.1.25 renamed from touch-doubleclick)
- [x] :touch-down
- [x] :touch-flick
- [x] :touch-long-click (ver. 0.1.25 renamed from touch-longclick)
- [x] :touch-move
- [x] :touch-scroll
- [x] :touch-up

## appium.lisp (ver. 0.1.24 split from api.lisp)
- [ ] :close-app (for appium command)
- [ ] :launch-app (for appium command)

## contexts.lisp  (ver. 0.1.24 merged from window.lisp and window-handle.lisp)
- [x] :close-window
- [x] :get-window-position-with-window-handle
- [x] :get-window-size
- [x] :get-window-size-with-window-handle
- [x] :maximize-window
- [x] :set-window-position-with-window-handle
- [x] :set-window-size
- [x] :set-window-size-with-window-handle
- [x] :window-maximize-with-window-handle
- [x] :get-window-handle
- [x] :get-window-handles

## document.lisp (ver. 0.1.24 renamed from source.lisp)
- [x] :get-source

## element-interaction.lisp (ver. 0.1.24 renamed from keys.lisp)
- [x] :send-keys
- [x] :send-string
- [x] :element-clear (ver. 0.1.24 moved from element.lisp)
- [x] :element-click (ver. 0.1.24 moved from element.lisp)
- [x] :element-send-keys (ver. 0.1.21 renamed from set-element-keys & moved from element.lisp)
- [x] :element-send-string

## element-retrieval.lisp (ver. 0.1.24 split from element.lisp)
- [x] :active-element
- [x] :find-element
- [x] :find-element-from-element
- [x] :find-elements
- [x] :find-elements-from-element

## element-state.lisp (ver. 0.1.24 split from element.lisp)
- [x] :element-equals
- [x] :get-element-attribute
- [x] :get-element-location
- [x] :get-element-location-in-view
- [x] :get-element-name
- [x] :get-element-size
- [x] :get-element-text
- [x] :is-element-displayed
- [x] :is-element-enabled
- [x] :is-element-selected

## location.lisp (ver. 0.1.26 split from actions.lisp)
- [ ] :location

## navigation.lisp (ver. 0.1.24 merged from api.lisp and title.lisp)
- [x] :back
- [x] :forward
- [x] :get-title

## orientation.lisp
- [x] :orientation

## screen-capture.lisp (ver. 0.1.21 renamed from screenshot.lisp)
- [x] :take-screenshot
- [x] :take-element-screenshot (ver. 0.1.21 moved from element.lisp)

## session.lisp
- [x] :delete-session
- [x] :get-sessions
- [x] :new-session

## status.lisp
- [x] :status

## timeouts.lisp
- [x] :set-timeouts
